# https://pre-commit.com/#new-hooks
# https://engineeringfordatascience.com/posts/pre_commit_yaml/

repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v4.4.0
  hooks:
    - id: trailing-whitespace
    - id: mixed-line-ending
    - id: check-added-large-files
      args: ['--maxkb=1000000']
    - id: end-of-file-fixer
    - id: requirements-txt-fixer
    - id: check-yaml
    - id: check-json
    - id: pretty-format-json
      args: ['--autofix']
    - id: check-merge-conflict
    - id: check-case-conflict
    - id: check-docstring-first
    - id: check-executables-have-shebangs
    - id: check-shebang-scripts-are-executable
    - id: detect-aws-credentials
    - id: detect-private-key
- repo: https://github.com/zricethezav/gitleaks
  rev: v8.15.1
  hooks:
    - id: gitleaks
# - repo: https://github.com/Lucas-C/pre-commit-hooks-nodejs
#   rev: v1.1.2
#   hooks:
#     - id: markdown-toc
# - repo: https://github.com/igorshubovych/markdownlint-cli
#   rev: v0.32.2
#   hooks:
#     - id: markdownlint
#     - id: markdownlint-fix
