name: CV Resumen from JSON to HTML

on:
  push:
    branches: [ main ]
    paths:
      - 'docs/cv/**'

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  check_run:
    runs-on: ubuntu-latest
    if: "! contains(github.event.head_commit.message, '[ci skip]')"
    steps:
      - run: echo "${{ github.event.head_commit.message }}"

  build:
    runs-on: ubuntu-latest
    needs: check_run
    steps:
      - uses: actions/checkout@v2
      - uses: kelvintaywl/action-jsonresume-export@v1
        name: Export resume as HTML
        with:
          theme: flat
          resume_filepath: docs/cv/resume.json
          # modifies the index.html in-place
          output_filepath: docs/cv/resume.html
      - uses: actions/upload-artifact@v3
        with:
          name: cv
          path: docs/cv/resume.html
