name: linksCheck
# runs every monday at 9 am
on:
  schedule:
    - cron: "0 9 * * 1"
  push:
    branches:
      - main
    # Paths can be used to only trigger actions when you have edited certain files, such as a file within the /docs directory
    paths:
      - docs/**
      - README.md
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  check-links:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: gaurav-nelson/github-action-markdown-link-check@v1
        # checks all markdown files from /docs including all subfolders
        with:
          use-quiet-mode: 'yes'
          use-verbose-mode: 'yes'
          config-file: '.github/workflows/markdown.links.config.json'
          folder-path: 'docs/'
          file-path: 'README.md'